### ISSUE TITLE
Dienstverlener attribuut niet correct gemapt

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLOthema-subsidies#14]
Volgens het applicatieprofiel Subsidieregister is het attribuut dienstverlener gemapt op http://data.europa.eu/m8g/serviceProvider (https://data.vlaanderen.be/doc/applicatieprofiel/subsidieregister/#Publieke%20Dienstverlening).

Een correcte vertaling ontbreekt momenteel in het vocabularium ns/subsidies:
https://data.vlaanderen.be/ns/subsidie/

**Comment by mvanbrab** [comment]
Het zal niet nodig zijn iets toe te voegen aan het vocabularium ns/subsidies, want "dienstverlener" is ontleend aan https://data.vlaanderen.be/ns/dienst. Dat kan je zien in de .eap (volgens Dimi deze: https://github.com/Informatievlaanderen/Data.Vlaanderen.be/blob/production/src/OSLO-Subsidie.eap). Daar staat bij de tags van de associatie "wordtUitgevoerdDoor" de uri http://data.europa.eu/m8g/serviceProvider, het label-nl "dienstverlener", maar ook package "OSLO-Dienst".

Opgelet bij verder werken aan dit vocabularium: "dienstverlener" staat in de UML ook als **rol** op de associatie "wordtUitgevoerdDoor.
De huidige spec werd gegenereerd met toolchain 1.0, waar rollen op associaties niet werden geïnterpreteerd.
Bij verder werken zal de spec allicht gegeneerd worden met toolchain 2.0 (+). Deze interpreteert rollen en verwacht bij aanwezigheid van een rol ook tags op het betreffende associatie-uiteinde.
**Dan dus de vermelde tags verplaatsen van de associatie naar de rol (en de associatienaam verwijderen).**
